use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PluginManifest {
    pub id: String,
    pub name: String,
    pub version: String,
    pub minimum_version: String,
    pub description: String,
    pub category: String,
    pub supported_phases: Vec<String>,
    pub supported_platforms: Vec<String>,
    pub required_binaries: Vec<String>,
    pub binary: String,
    pub system_binary: Option<String>,
    pub managed_binary: Option<String>,
    pub capabilities: Vec<String>,
    pub workflow_categories: Vec<String>,
    pub health_command: String,
    pub verification_command: String,
    pub installation_metadata: String,
    pub update_strategy: String,
    pub parser_configuration: String,
    pub risk_level: String,  // Low, Medium, High
    pub noise_level: String, // Quiet, Moderate, Loud
    pub install_methods: Vec<String>,
    pub default_arguments: Vec<String>,
    pub author: String,
    pub license: String,
}

impl PluginManifest {
    pub fn get_builtins() -> Vec<Self> {
        vec![
            Self {
                id: "nmap".into(),
                name: "nmap".into(),
                version: "7.94".into(),
                minimum_version: "7.80".into(),
                description: "Network mapper for port discovery, service detection, and OS fingerprinting.".into(),
                category: "Recon & Enumeration".into(),
                supported_phases: vec!["Reconnaissance".into(), "Enumeration".into()],
                supported_platforms: vec!["Linux".into(), "Windows".into(), "macOS".into()],
                required_binaries: vec!["nmap".into()],
                binary: "nmap".into(),
                system_binary: Some("/usr/bin/nmap".into()),
                managed_binary: Some("~/.zephyx/bin/nmap".into()),
                capabilities: vec!["port scan".into(), "service detection".into(), "os fingerprinting".into()],
                workflow_categories: vec!["recon".into(), "enumeration".into()],
                health_command: "nmap --version".into(),
                verification_command: "nmap --help".into(),
                installation_metadata: "apt install nmap".into(),
                update_strategy: "apt update".into(),
                parser_configuration: "nmap_xml_parser".into(),
                risk_level: "Low".into(),
                noise_level: "Moderate".into(),
                install_methods: vec!["apt install nmap".into(), "brew install nmap".into()],
                default_arguments: vec!["-sCV".into(), "-oX".into(), "-".into()],
                author: "Gordon Lyon (Fyodor)".into(),
                license: "NPSL".into(),
            },
            Self {
                id: "rustscan".into(),
                name: "rustscan".into(),
                version: "2.1.1".into(),
                minimum_version: "2.0.0".into(),
                description: "Ultra-fast modern port scanner built in Rust that pipes findings directly to Nmap.".into(),
                category: "Recon".into(),
                supported_phases: vec!["Reconnaissance".into()],
                supported_platforms: vec!["Linux".into(), "macOS".into()],
                required_binaries: vec!["rustscan".into()],
                binary: "rustscan".into(),
                system_binary: Some("/usr/bin/rustscan".into()),
                managed_binary: Some("~/.zephyx/bin/rustscan".into()),
                capabilities: vec!["fast port discovery".into(), "nmap integration".into()],
                workflow_categories: vec!["recon".into()],
                health_command: "rustscan --version".into(),
                verification_command: "rustscan --help".into(),
                installation_metadata: "cargo install rustscan".into(),
                update_strategy: "cargo install rustscan --force".into(),
                parser_configuration: "rustscan_parser".into(),
                risk_level: "Low".into(),
                noise_level: "Loud".into(),
                install_methods: vec!["cargo install rustscan".into()],
                default_arguments: vec!["-a".into()],
                author: "Bee".into(),
                license: "GPL-3.0".into(),
            },
            Self {
                id: "ffuf".into(),
                name: "ffuf".into(),
                version: "2.1.0".into(),
                minimum_version: "2.0.0".into(),
                description: "Fast web fuzzer written in Go for discovering hidden directories, files, and virtual hosts.".into(),
                category: "Web Enumeration".into(),
                supported_phases: vec!["Enumeration".into()],
                supported_platforms: vec!["Linux".into(), "Windows".into(), "macOS".into()],
                required_binaries: vec!["ffuf".into()],
                binary: "ffuf".into(),
                system_binary: Some("/usr/bin/ffuf".into()),
                managed_binary: Some("~/.zephyx/bin/ffuf".into()),
                capabilities: vec!["directory brute force".into(), "vhost fuzzing".into(), "json export".into()],
                workflow_categories: vec!["web".into(), "enumeration".into()],
                health_command: "ffuf -V".into(),
                verification_command: "ffuf -h".into(),
                installation_metadata: "go install github.com/ffuf/ffuf/v2@latest".into(),
                update_strategy: "go install github.com/ffuf/ffuf/v2@latest".into(),
                parser_configuration: "ffuf_json_parser".into(),
                risk_level: "Low".into(),
                noise_level: "Moderate".into(),
                install_methods: vec!["go install github.com/ffuf/ffuf/v2@latest".into(), "apt install ffuf".into()],
                default_arguments: vec!["-u".into(), "http://target/FUZZ".into()],
                author: "joohoi".into(),
                license: "MIT".into(),
            },
            Self {
                id: "gobuster".into(),
                name: "gobuster".into(),
                version: "3.6.0".into(),
                minimum_version: "3.0.0".into(),
                description: "Directory/File, DNS and VHost brute-forcing tool written in Go.".into(),
                category: "Web Enumeration".into(),
                supported_phases: vec!["Enumeration".into()],
                supported_platforms: vec!["Linux".into(), "Windows".into(), "macOS".into()],
                required_binaries: vec!["gobuster".into()],
                binary: "gobuster".into(),
                system_binary: Some("/usr/bin/gobuster".into()),
                managed_binary: Some("~/.zephyx/bin/gobuster".into()),
                capabilities: vec!["directory brute force".into(), "dns fuzzing".into(), "virtual hosts".into()],
                workflow_categories: vec!["web".into(), "enumeration".into()],
                health_command: "gobuster version".into(),
                verification_command: "gobuster --help".into(),
                installation_metadata: "apt install gobuster".into(),
                update_strategy: "apt update && apt install --only-upgrade gobuster".into(),
                parser_configuration: "gobuster_parser".into(),
                risk_level: "Low".into(),
                noise_level: "Moderate".into(),
                install_methods: vec!["apt install gobuster".into()],
                default_arguments: vec!["dir".into(), "-u".into()],
                author: "OJ Reeves".into(),
                license: "Apache-2.0".into(),
            },
            Self {
                id: "enum4linux".into(),
                name: "enum4linux".into(),
                version: "0.5.5".into(),
                minimum_version: "0.5.0".into(),
                description: "Tool for enumerating information from Windows and Samba systems.".into(),
                category: "SMB Enumeration".into(),
                supported_phases: vec!["Enumeration".into()],
                supported_platforms: vec!["Linux".into()],
                required_binaries: vec!["enum4linux".into()],
                binary: "enum4linux".into(),
                system_binary: Some("/usr/bin/enum4linux".into()),
                managed_binary: Some("~/.zephyx/bin/enum4linux".into()),
                capabilities: vec!["smb enumeration".into(), "user enumeration".into(), "share enumeration".into()],
                workflow_categories: vec!["smb".into(), "active-directory".into()],
                health_command: "enum4linux -h".into(),
                verification_command: "enum4linux -h".into(),
                installation_metadata: "apt install enum4linux".into(),
                update_strategy: "apt update".into(),
                parser_configuration: "enum4linux_parser".into(),
                risk_level: "Low".into(),
                noise_level: "Loud".into(),
                install_methods: vec!["apt install enum4linux".into()],
                default_arguments: vec!["-a".into()],
                author: "Mark Lowe".into(),
                license: "GPL-2.0".into(),
            },
        ]
    }
}
